# -*- coding: utf-8 -*-

sudo: false

language: python
python:
  - "3.6"
  - "3.5"
  - "2.7"

before_install:
  - pip --version

install:
  - pip install tox
  - pip install coveralls

script:
  - if [[ $TRAVIS_PYTHON_VERSION == '3.6' ]]; then tox -e py36; fi
  - if [[ $TRAVIS_PYTHON_VERSION == '3.5' ]]; then tox -e py35; fi
  - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then tox -e py27; fi

after_success:
  - coveralls
